version: '3'
services:
  # db:
  #   image: postgres:latest
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   restart: always
  #   environment:
  #     POSTGRES_DB: postgress
  #     POSTGRES_PASSWORD: postgress
  #     POSTGRES_USER: postgress
  #   ports:
  #     - "5432:5432"
  marple:
    build: marple
    container_name: marple
    volumes:
      - ./marple/central-lucene-index:/central-lucene-index
    ports:
      - 9300:8080

  libsearch:
    build: libsearch_app
    container_name: libsearch_app
    volumes:
      - ./libsearch_app:/home/libsearch

  elasticsearch:
    build: elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      # - cluster.name=docker-cluster
      # - bootstrap.memory_lock=true
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.3
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    ports:
      - 5601:5601
    links:
      - "elasticsearch:elasticsearch"
    depends_on:
      - elasticsearch
volumes:
  db_data:
  es_data: